- name: Play level variables
  hosts: local
  connection: local
  become: yes
  vars:
    FIRST_NAME: "Vinodkumar"
    LAST_NAME: "Paleti"
    DOB: "01-06-1992"
  tasks:
    - name: print the variables
      ansible.builtin.debug:
        msg: "You Name is: {{ FIRST_NAME }} {{ LAST_NAME }}, your DOB: {{ DOB }}"