- name: argument level variables
  hosts: local
  connection: local
  tasks:
    - name: print the variables from args
      ansible.builtin.debug:
        msg: "Hi {{ NAME }}, Good Morning"  # Here we should pass the variable on the CLI as an argument during running the playbook