- name: Check the vars preference
  hosts: local
  connection: local
  become: yes
  vars:
    NAME: "Ansible from Playbook level"
  vars_files:
    - details.yaml
  vars_prompt:
    name: NAME
    prompt: Please enter your message
    private: false
  tasks:
    - name: "Print the variable from task level"
      vars:
        NAME: "Ansible from Task level"
      ansible.builtin.debug:
        msg: "Hi {{ NAME }}"