- name: ansible loops
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: iterate the values in a loop
      ansible.builtin.debug:
        msg: "Hello {{ item }}"    # Here 'item' keyword is static or fixed.
      loop:
        - Paleti
        - Vinod
        - Kumar